---
name: Python package

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8.0, 3.8.2, 3.8.3]

    steps:
    - uses: actions/checkout@v2.1.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make init
    - name: Lint
      run: |
        make lint
    - name: Type checking with mypy
      run: |
        make typing
    - name: Test coverage
      run: |
        make coverage
    - uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{secrets.CODECOV}}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
